TREE1_ADDR=$1
TREE2_ADDR=$2
OUTPUT_ADDR=$3
NUMBER_OF_ARTICLES_TO_SAMPLE="100"
SAMPLED_ARTS_ADDR=$OUTPUT_ADDR"/sampled_arts.txt"
SIMILARITY_SCORE_ADDR=$OUTPUT_ADDR"/reported_similartity.txt"
./a.out $TREE1_ADDR $TREE2_ADDR $OUTPUT_ADDR $NUMBER_OF_ARTICLES_TO_SAMPLE
./b.out $TREE1_ADDR $TREE2_ADDR $SAMPLED_ARTS_ADDR $OUTPUT_ADDR 0
./c.out $SIMILARITY_SCORE_ADDR $OUTPUT_ADDR
